#!/bin/bash

# $1 = output.
# $2 = directory.
# $3 = extension.

RED='\033[0;31m'
NC='\033[0m'

if [ $# -eq 3 ]
then
	if [ ! -d $2 ]
	then
		{
			echo -e "${RED}!ERROR!${NC}"
			echo "$2 : this directory doesn't exist" 
		}>&2
	else
		find $2 -maxdepth 1 -type f -name "*.$3" -printf "%f\n" | sort -d >$1
	fi
else
	{
		echo -e "${RED}!ERROR!${NC}"
		echo "First argument = output file path."
		echo "Second argument = directory path."
		echo "Third argument = file extension." 
	}>&2
fi
